# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'code-coverage':
    docker:
      - image: circleci/node:10
    working_directory: ~/loader
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      # - run: npm install
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
      # - run: yarn cov:send
      # - run: yarn cov:check
  # 'build':
  # 'deploy-npm':


workflows:
  version: 2
  test:
    jobs:
      - 'code-coverage':
          filters:
            branches:
              only:
                - master
  # build-n-deploy:
  #   jobs:
  #     - 'build':
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - 'deploy-npm':
  #         filters:
  #           branches:
  #             only:
  #               - master
